### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by zhangyu68** [facingwaller/deeplearning#1]
I am a graduate student in grade two.
emmmm...
都是中国人，我写不下去英文了哈哈哈！
因为要以KBQA为研究课题做毕业设计。觉得您好厉害！请问能加个联系方式请教吗？

**Comment by facingwaller** [comment]
?? 

> I am a graduate student in grade two.
> emmmm...
> 都是中国人，我写不下去英文了哈哈哈！
> 因为要以KBQA为研究课题做毕业设计。觉得您好厉害！请问能加个联系方式请教吗？

给下你的邮箱

**Comment by facingwaller** [comment]
done
